engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/PerceivedComplexity:
        Max: 10
      Rubocop/Metrics/AbcSize:
        Max: 20
      Rubocop/Style/SingleLineMethods:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Metrics/MethodLength:
        enabled: false
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
      Rubocop/Style/TrailingBlankLines:
        enabled: false
      Rubocop/Style/IndentationWidth:
        enabled: false
      Rubocop/Style/Not:
        enabled: false
      Rubocop/Style/SpaceInsideBlockBraces:
        enabled: false
      Rubocop/Style/TrailingWhitespace:
        enabled: false
      Rubocop/Style/AndOr:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/MethodDefParentheses:
        enabled: false
      Rubocop/Style/NumericPredicate:
        enabled: false
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
exclude_paths:
  - test/
