engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    # channel: rubocop-0-48
    # config:
      # file: .rubocop-custom.yml
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- test/
