engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/SingleLineMethods:
        enabled: false
      Rubocop/Metrics/ClassLength:
        enabled: false
      Rubocop/Metrics/MethodLength:
        enabled: false
      Rubocop/Metrics/PerceivedComplexity:
        Max: 10
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - test/
